### ISSUE TITLE
error download torrent

### ISSUE THREAD

**Issue by zoreu** [Mys7erio/aiotorrent#5]
log:

`Traceback (most recent call last):
  File "C:\Users\Joel\Desktop\client_torrent\example.py", line 65, in <module>
    asyncio.run(main())
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Joel\Desktop\client_torrent\example.py", line 42, in main
    await torrent.init()
  File "C:\Users\Joel\Desktop\client_torrent\aiotorrent\aiotorrent.py", line 126, in init
    await self._contact_trackers()
  File "C:\Users\Joel\Desktop\client_torrent\aiotorrent\aiotorrent.py", line 102, in _contact_trackers
    await asyncio.gather(*task_list)
  File "C:\Users\Joel\Desktop\client_torrent\aiotorrent\core\trackers.py", line 202, in get_peers
    await loop.create_datagram_endpoint(
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1296, in create_datagram_endpoint
    infos = await self._ensure_resolved(
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1396, in _ensure_resolved
    return await loop.getaddrinfo(host, port, family=family, type=type,
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 856, in getaddrinfo
    return await self.run_in_executor(
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\concurrent\futures\thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Joel\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed`

**Comment by Mys7erio** [comment]
Hi can you please provide more info on this issue and also how to reproduce this issue?
